### PR TITLE
DRAFT: Wip, prototype

### PR DESCRIPTION
**Pull request by FaveroFerreira**
wip for [gklijs/schema_registry_converter/issues#104](https://github.com/gklijs/schema_registry_converter/issues/104)

### CODE REVIEW

**Comment by FaveroFerreira** [comment]
@gklijs This is how it is comming together, care to share your opinions?@gklijs This is how it is coming together, care to share your opinions?

**Comment by gklijs** [comment]
I only had little time, but it's looking great. I think it should be fine to move to async only, and having seperate crates makes it easier to use compares to features. There are some added dependencies like for logging an tracing that make a lot of sense.

As this is becoming quite big I do have two things:
- please don't upgrade `logos` yet, I'll try to make an issue to upgrade and make the changes to the proto resolver.
- It would be nice to have some minimal performance test running on GitHub actions. I might have time this weekend to add something. I want to be sure for this pr, but also future pr's we don't have a drop in performance.

**Comment by FaveroFerreira** [comment]
@gklijs welp, protobuf is a pain to work with... I am not a big conosseur of protobuf myself, but it doesn't seem like there is a lot of support for protobuf in Rust.

Ill try to bench our possible solutions using Logos and other alternatives like Nom.

**Comment by gklijs** [comment]
Indeed, I still remember I promised to add JSON Schema and Protobuf support for a Kafka Summit talk. When close to the deadline, I needed the proto resolver code for something which is just a few lines in the Java code. Things might have improved through. For now, it's fine to just copy-paste the resolver to the protobuf module? We can update and/or take an alternative approach in another pr.

**Comment by FaveroFerreira** [comment]
Yeah, I think we can do with a copy paste for now. Ill add it latter this week and wrap up the parsed schema cache.

**Comment by gklijs** [comment]
How are you doing? I also saw the blocking approach on the main branch is the likely cause of it's failing to upgrade `reqwest` now. So the rewrite will also take care of that. I have little time myself, unfortunately.

**Comment by FaveroFerreira** [comment]
Sorry for my late response, my father was diagnosed with cancer so my side projects got put on hold. Now I am back, and I'm still interested in finishing this thing. 

However, I've been thinking about dropping protobuf support tbh. I dont think I have the necessary knowlege or skills to do it.

Maybe we should make this a different crate, so the current schema_registry_converter does not drop active features?

What do you think @gklijs ?

**Comment by gklijs** [comment]
Sorry to hear that. A niece of mine is going trough cancer for the second time, this time terminal. It's a cruel way to (almost) lose your life.
A different crate, just for async, avro, sounds fine to me. That way you don't need any feature flags, and it can be a lot simpler. I do would like to prefer to be as backwards compatible as possible. And not loose major features like JSON schema and Protobuf support. Another possibility is to start out with a seperate schema registry client, using code generation. I know that were some requests to support other calls to schema registry. By using the open api definition, you would have them all. And a good schema registry client can in turn be used by this or other libraries.

**Comment by FaveroFerreira** [comment]
I'm so sorry man. May time be generous and bring you the comfort you need, as it did to me.

As you suggested, I've started a standalone schema registry client, that is complient with the schema registry API. The openapi file they provide is incomplete in comparison with the [docs](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#config).

You can keep track of progress in this [repo](https://github.com/faveroferreira/schema-registry).

**Pull request closed without merging**
